apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: radicale
resources:
  - ./base/
images:
  - name: radicale
    newName: drgrovellc/radicale
    digest: sha256:055e686577ec543b33ff905b09f798a3a178393c14799a85867d86519a8d0a35
